# Generated by Django 4.2.4 on 2023-08-22 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_divisi', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('nama', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=25)),
                ('position', models.CharField(choices=[('direksi', 'Direksi'), ('manajer', 'Manajer'), ('staff', 'Karyawan Outsourcing')], max_length=40)),
                ('jenis_karyawan', models.CharField(choices=[('tetap', 'Karyawan Tetap'), ('freelance', 'Freelancer'), ('outsourcing', 'Karyawan Outsourcing')], max_length=40)),
                ('divisi', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaji_app.divisi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('gaji_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bulan', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True)),
                ('jml_hari_kerja', models.IntegerField(default=0)),
                ('gaji_pokok', models.IntegerField(null=True)),
                ('tunjangan_sakit', models.IntegerField(null=True)),
                ('tunjangan_cuti', models.IntegerField(null=True)),
                ('tunjangan_makan', models.IntegerField(null=True)),
                ('tunjangan_transport', models.IntegerField(null=True)),
                ('total_gaji', models.IntegerField(null=True)),
                ('nip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaji_app.karyawan', to_field='nip')),
            ],
        ),
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('absen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(null=True)),
                ('keterangan', models.CharField(choices=[('masuk', 'Masuk'), ('sakit', 'Sakit'), ('izin', 'Izin'), ('cuti', 'Cuti')], max_length=20)),
                ('nip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaji_app.karyawan', to_field='nip')),
            ],
        ),
    ]
